### ISSUE TITLE
Criar menu da Landing 1

### ISSUE THREAD

**Issue by renanmonsi** [renanmonsi/clubederevistas#3]
Apenas desktop:

![image](https://user-images.githubusercontent.com/3473078/116447679-9f545c00-a82e-11eb-919d-c014cd30ec87.png)

**Comment by leogiraldimg** [comment]
@renanmonsi implementado o header de forma responsiva. Favor validar e confirmar se posso fechar o issue

**Comment by renanmonsi** [comment]
Ta perfeito, bora!
