### ISSUE TITLE
Criar carrossel de marcas

### ISSUE THREAD

**Issue by renanmonsi** [renanmonsi/clubederevistas#5]
O carrossel deve rodar lentamente da esquerda para a direita.

![image](https://user-images.githubusercontent.com/3473078/116448215-3ae5cc80-a82f-11eb-90d8-1c3c7293edc6.png)

![image](https://user-images.githubusercontent.com/3473078/116448237-42a57100-a82f-11eb-8e2a-c0c963134106.png)

**Comment by leogiraldimg** [comment]
Carrosel criado: 
![image](https://user-images.githubusercontent.com/38134909/116791704-8fd54d00-aa92-11eb-9b37-5abc44322886.png)

![image](https://user-images.githubusercontent.com/38134909/116791712-9a8fe200-aa92-11eb-9e9c-b17da8cac638.png)

**Comment by leogiraldimg** [comment]
@renanmonsi  favor validar :)
