### ISSUE TITLE
Criar sessão de "Vantagens do clube"

### ISSUE THREAD

**Issue by renanmonsi** [renanmonsi/clubederevistas#6]
No mobile, os itens de vantagens devem se tornar um carrossel sem loop.

![image](https://user-images.githubusercontent.com/3473078/116448408-77b1c380-a82f-11eb-940b-0a8baf96f54b.png)

![image](https://user-images.githubusercontent.com/3473078/116448433-7f716800-a82f-11eb-826c-772acef08c5a.png)

**Comment by leogiraldimg** [comment]
Abertura do modal no botão do vídeo

**Comment by leogiraldimg** [comment]
@renanmonsi finalizada. Favor validar
