### ISSUE TITLE
Criar modal para link "Assista ao video e saiba mais"

### ISSUE THREAD

**Issue by renanmonsi** [renanmonsi/clubederevistas#7]
Não temos o layout para essa parte. Devemos criar um modal em tela cheia para exibir o video.

![image](https://user-images.githubusercontent.com/3473078/116448749-d5dea680-a82f-11eb-975a-87c9eea606e3.png)

![image](https://user-images.githubusercontent.com/3473078/116448590-aaf45280-a82f-11eb-9865-59fcb6ac7ed5.png)

**Comment by leogiraldimg** [comment]
@renanmonsi finalizado, favor validar:

![image](https://user-images.githubusercontent.com/38134909/116791795-01ad9680-aa93-11eb-8e85-63a7c23c141f.png)
![image](https://user-images.githubusercontent.com/38134909/116791802-0e31ef00-aa93-11eb-85ee-d8db16a516cf.png)
